//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.11.15 at 11:05:06 PM EST
//


package org.autopipes.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {})
@XmlRootElement(name = "render-dwg")
public class RenderDwg {
	@XmlElement(name = "dwg-id")
    protected Long drawingId;
	@XmlElement(name = "area-id")
    protected Long areaId;
    @XmlElement(name = "main-labels")
    protected Boolean mainLabels;
    @XmlElement(name = "branch-labels")
    protected Boolean branchLabels;
    @XmlElement(name = "main-breakups")
    protected Boolean mainBreakups;
    @XmlElement(name = "branch-breakups")
    protected Boolean branchBreakups;
    @XmlElement(name = "main-e2e")
    protected Boolean mainE2E;
    @XmlElement(name = "branch-e2e")
    protected Boolean branchE2E;
    @XmlElement(name = "main-spans")
    protected Boolean mainSpans;
    @XmlElement(name = "branch-spans")
    protected Boolean branchSpans;
    @XmlElement(name = "branch-heads")
    protected Boolean branchHeads;

    public Boolean isMainLabels() {
        return mainLabels;
    }

    public void setMainLabels(final Boolean value) {
        this.mainLabels = value;
    }

    public Boolean isBranchLabels() {
        return branchLabels;
    }

    public void setBranchLabels(final Boolean value) {
        this.branchLabels = value;
    }

    public Boolean isMainBreakups() {
        return mainBreakups;
    }

    public void setMainBreakups(final Boolean value) {
        this.mainBreakups = value;
    }

    public Boolean isBranchBreakups() {
        return branchBreakups;
    }

    public void setBranchBreakups(final Boolean value) {
        this.branchBreakups = value;
    }


    public Boolean isMainE2E() {
		return mainE2E;
	}

	public void setMainE2E(Boolean mainE2E) {
		this.mainE2E = mainE2E;
	}

	public Boolean isBranchE2E() {
		return branchE2E;
	}

	public void setBranchE2E(Boolean branchE2E) {
		this.branchE2E = branchE2E;
	}

	public Boolean isMainSpans() {
        return mainSpans;
    }

    public void setMainSpans(final Boolean value) {
        this.mainSpans = value;
    }

    public Boolean isBranchSpans() {
        return branchSpans;
    }

    public void setBranchSpans(final Boolean value) {
        this.branchSpans = value;
    }

    public Boolean isBranchHeads() {
        return branchHeads;
    }

    public void setBranchHeads(final Boolean value) {
        this.branchHeads = value;
    }

    public Long getDrawingId() {
		return drawingId;
	}

	public void setDrawingId(final Long drawingId) {
		this.drawingId = drawingId;
	}

	public Long getAreaId() {
		return areaId;
	}

	public void setAreaId(final Long areaId) {
		this.areaId = areaId;
	}

}
