//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.11.15 at 11:05:06 PM EST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dwg.autopipes.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED)
package org.autopipes.takeout;
